

- Database:
    db_type: mssql+pyodbc
    driver: '{SQL SERVER}'
    server: DESKTOP-BMEMTUQ\SQLEXPRESS
    database: STATCAST

- Paths:
    parent_path: C:/Users/okiem/OneDrive/Desktop/The_Project_Folder/mlb-statcast-ml
