

- Database_System:
    db_type: mysql

- DB_MSSQL:
    driver: '{SQL SERVER}'
    server: DESKTOP-BMEMTUQ\SQLEXPRESS
    database: STATCAST

- DB_MySQL:
    username: root
    password: Hh6994hh!
    server: localhost
    database: statcast

- Paths:
    parent_path: C:/Users/okiem/github/mlb-statcast-ml
